### ISSUE TITLE
Remove restriction for client id max length 25 chars

### ISSUE THREAD

**Issue by PHameete** [DRIVER-EU/test-bed-admin#13]
As the title says. Can we remove or increase the char limit for client id's? This is currently too error prone, because if a user of an adapter chooses an id over 25 chars the entire test-bed-admin will not work.

**Comment by JoaquinMB-Freq** [comment]
Thanks @PHameete!!!

@tobritzh can you please take care of it?

B.R.

**Comment by tobritzh** [comment]
client ID length is changed to 255 char.
