### ISSUE TITLE
Websocket connection fails on driver-testbed.eu

### ISSUE THREAD

**Issue by rinzeb** [DRIVER-EU/test-bed-admin#16]
The admin-tool does not work when it is hosted on the driver-testbed.eu website. When opening the admin tool in a browser, it tries to make a websocket connection to ws://localhost:8090.

![image](https://user-images.githubusercontent.com/11523459/45357364-4de7f780-b5c6-11e8-9c16-91ecebcf8e3b.png)

**Comment by PHameete** [comment]
Solution would be to provide via ENV variable the hostname/port where the admin tool can be reached (for example: driver-testbed.eu:8090)

**Comment by thoobr** [comment]
WebSocket working.
