### ISSUE TITLE
Make frontend resource paths relative

### ISSUE THREAD

**Issue by PHameete** [DRIVER-EU/test-bed-admin#17]
For work on the test-bed compositions to make the services of the test-bed available on more user friendly URLs it will be possible to access the test-bed admin tool from a relative path, for example:

`http://tb1.driver-testbed.eu/admin-tool/`

However, currently the admin tool Frontend requests it resources using absolute pathing, for example requesting resources at:

'http://tb1.driver-testbed.eu/static/css/app.52e49e37aef43ba6d3600598ba1a1e3a.css'

This should be:

'http://tb1.driver-testbed.eu/admin-tool/static/css/app.52e49e37aef43ba6d3600598ba1a1e3a.css'

A fix should be as easy as removing a prefix '/' for the resource links.

**Comment by hannahgoeritz** [comment]
I'm not sure i understand what you mean by "removing a prefix '/'"?

**Comment by hannahgoeritz** [comment]
ooh the second i wrote my comment i got an idea of what you meant :p 
did you mean that because of the '/' currently the path would result int admin-tool//static (with two '/') instead of admin-tool/static?

**Comment by PHameete** [comment]
No, if the path to a resouce (i.e. js, css or websocket) starts with a / it will start from the root of the domain.

However, if it doesn't start with a / it the path will start from the current path. For example if you refer from the page driver-testbed.eu/admin-tool/ to a resource with `/static/resources/test.css` it will look for the resource at driver-testbed.eu/static/resources/test.css. This doesn't work if the admin-tool is hosted at a relative path /admin-tool/.

If you refer with `static/resource/test.css` it will look at driver-testbed.eu/admin-tool/static.resource/test.css which should work.

I'm not sure if the above also holds for the tools that you are using, but usually that's the case :-)

**Comment by PHameete** [comment]
Hey @hannahgoeritz , what is the status on this?

**Comment by hannahgoeritz** [comment]
@thoobr needs to release a new version. He is currently on vacation and will be back next week.

**Comment by thoobr** [comment]
Preparing the new release, in this we will also change the StartTrial button to send the invites again if needed.

**Comment by thoobr** [comment]
Done
