### ISSUE TITLE
Admin tool (and AAR) become unresponsive when there are too many log messages

### ISSUE THREAD

**Issue by erikvullings** [DRIVER-EU/test-bed-admin#18]
![image](https://user-images.githubusercontent.com/3140667/56288435-170b2e80-611f-11e9-830a-4c84f53abe4a.png)
For tb5, I've tried to initialize the Trial, but it fails (page becomes unresponsive), presumably because there are too many messages in the log. Same for the AAR.

**Comment by thoobr** [comment]
Add paging for the logs as for the AAR records.
Backend is already available:

public ResponseEntity<LogList> getAllLogs(@RequestParam(value="page", required=false) Integer page, @RequestParam(value="size", required=false) Integer size) {

public ResponseEntity<Double> getPageCount() {

**Comment by croser** [comment]
Done, please test - as my local database had only less than page size entries.

**Comment by thoobr** [comment]
works
