### ISSUE TITLE
Testbed configuration overview

### ISSUE THREAD

**Issue by thoobr** [DRIVER-EU/test-bed-admin#22]
Add a button in the menu bar to display the testbed overview picture (SVG).
The picture can be retrieved by HTTP GET: /AdminService/createOverviewPicture

Display the picture in a separate tab and make is downloadable.

**Comment by croser** [comment]
@thoobr: Implementation of client should be done, but could not be tested properly due to an empty SVG response retrieved from the server. Please check + test + hand this ticked back to me in case of any issues.

**Comment by thoobr** [comment]
SVG is not available.

**Comment by croser** [comment]
Can you please clarify? 
For me this rather appears as a server issue as GET /AdminService/createOverviewPicture?t=1568839200562&v=0 returns the following (empty 10x10) SVG:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" contentScriptType="application/ecmascript" contentStyleType="text/css" height="10px" preserveAspectRatio="none" style="width:10px;height:10px;" version="1.1" viewBox="0 0 10 10" width="10px" zoomAndPan="magnify"><defs/><g/></svg>
```

If I change its background color to red, i see the SVG in the page that is opened on the web browser.

**Comment by thoobr** [comment]
Overview picture is displayed
