### ISSUE TITLE
Edit button

### ISSUE THREAD

**Issue by croser** [DRIVER-EU/test-bed-admin#31]
* For solution, topic, gateway:
  * Add edit button left of status icon
  * Same form as for "New"
  * Endpoints

HTTP PUT
/AdminService/updateSolution
/AdminService/updateTopic
/AdminService/updateGateway

**Comment by croser** [comment]
Note: endpoints for creation:

HTTP POST:
/AdminService/addSolution
/AdminService/addTopic
/AdminService/addGateway

**Comment by thoobr** [comment]
Edit Solution is not working correct:
solution in the getAllTrialSolution is ok:
![image](https://user-images.githubusercontent.com/16935688/68289054-c2f97480-0085-11ea-8d0e-394425fa3f6e.png)

But in the solution that is submitted for update are missing isAdmin, state and organisation:
![image](https://user-images.githubusercontent.com/16935688/68289267-1c61a380-0086-11ea-967e-28c4e246799e.png)
