### ISSUE TITLE
Remove button

### ISSUE THREAD

**Issue by croser** [DRIVER-EU/test-bed-admin#32]
* For solution, topic, gateway:
   * Add remove button left of status icon
   * Endpoints:

HTTP DELETE:
/AdminService/removeSolution/{id}
/AdminService/removeTopic/{id}
/AdminService/removeGateway/{id}

**Comment by croser** [comment]
@thoobr: Please provide details on endpoint

**Comment by thoobr** [comment]
HTTP DELETE:
/AdminService/removeSolution/{id}
/AdminService/removeTopic/{id}
/AdminService/removeGateway/{id}
