### ISSUE TITLE
Create & download certificate

### ISSUE THREAD

**Issue by croser** [DRIVER-EU/test-bed-admin#33]
* For solution
  * Add create certificate & download certificate buttons
  * Endpoints:
    * GET /AdminService/createSolutionCertificate? clientID=<solution.clientID>&organisationName=<solution.orgName>&password=<solution.certPwd>&email=<solution.email>: returnValue is certificate file name
    * GET /AdminService/downloadCertificate/{fileName}: .p12 file

**Comment by croser** [comment]
@thoobr: Please provide me with a JSON certJson as retrieved from 8443 for testing. Thanks!

**Comment by croser** [comment]
@thoobr : Basic functionality is there. We hold the collection of certificate file names in-browser-memory for now. Please let me know as soon as a endpoint is available delivering the initial state of certificate files (i.e. a map<solution, fileName>)

**Comment by thoobr** [comment]
Endpoint id available:
HTTP GET: /AdminService/getSolutionsCertMap
RETURNS: Map<String,String> -> key = clientID, value=p12 filename e.g.: test.p12
