### ISSUE TITLE
Extend solution form

### ISSUE THREAD

**Issue by croser** [DRIVER-EU/test-bed-admin#34]
Extend solution form by:

* orgName: GET /AdminService/getAllOrganisations returns list of possible organisations for drop down
* ~~username~~
* ~~userPwd~~
* ~~certPwd~~
* ~~email~~

**Comment by thoobr** [comment]
Only display:
orgName: GET /AdminService/getAllOrganisations returns list of possible organisations for drop down

The other data should be displayed in the Organisation Dialog.

**Comment by croser** [comment]
That is fine, however: where do we take information on parameters from for #33 then?
