### ISSUE TITLE
change websocket library

### ISSUE THREAD

**Issue by thoobr** [DRIVER-EU/test-bed-admin#36]
We need to use socket.io library for WebSocket sommunication to the backend to run the backend behind a apache revers proxy

**Comment by croser** [comment]
imho it is easier to use sockjs for reverse proxy support of real-time-communication, as sockjs is supported by spring (boot) out of the box. 

please test web socket communications.

**Comment by thoobr** [comment]
WebSocket is not working on admin tool
I get following Error:
WebSocket connection to 'ws://localhost:8090/AdminServiceWSEndpoint' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by thoobr** [comment]
OK, websocket are working, a complete clean and build solvet the issue.
I saw that the update of the solution and topic state was not working, the issue was in the finding the obj:
const obj = state.topics.find(obj => obj.id=== payload.id);
should be:
const obj = state.topics.find(obj => obj.clientId === payload.id);

I corrected this. Update is now working,  but the topic name is gone after the update:
![image](https://user-images.githubusercontent.com/16935688/68652264-5b31a680-0529-11ea-8e53-2e51ff5d3de6.png)

**Comment by croser** [comment]
@thoobr: Can you briefly describe the steps how i can reproduce/test that?
We should not have changed anything in the communicated contents, so this issue might have been there already for some time.

**Comment by thoobr** [comment]
Just start the application and press the Initialize button. the topics state is true (green) but the name is gone. Pls check that following entry is in the config/client.properties file:
zookeeper.simulate.creation=true
