### ISSUE TITLE
Rename "Initialize trial" to "Initialize test-bed"

### ISSUE THREAD

**Issue by erikvullings** [DRIVER-EU/test-bed-admin#4]
Since the trial initialization requires more, e.g. simulators need to be configured too. In addition, I would also like to use our test-bed for exercises, not only trials.

**Comment by hannahgoeritz** [comment]
There is no such thing as "Initialize trial". 
Existing possibilities are: "Initialize testbed" and "Start trial".

**Comment by erikvullings** [comment]
Typo, I meant "Initialize testbed" to "Initialize test-bed" (with a dash).
