### ISSUE TITLE
State comparison

### ISSUE THREAD

**Issue by erikvullings** [DRIVER-EU/test-bed-admin#5]
When a trial (test-bed) is working fine, e.g. during a dry run, it would be nice if we could record the state (topics, services running etc) somehow, so we can later compare it to the actual state during the trial, and especially see the differences.

**Comment by tobritzh** [comment]
We will write the actual state (and all state changes) into the log.

**Comment by erikvullings** [comment]
Does this allow us to recover the state, i..e compare a working state (during dry run 2, for example), to the current state (before trial)?

**Comment by thoobr** [comment]
State are stored in the Admin Tool and also published to AAR.
